const state = { index: 0, mode: 'learn', answers: JSON.parse(localStorage.getItem('ab620-answers') || '{}'), query: '', topic: 'all' };
const $ = (selector) => document.querySelector(selector);
const themeSelect = $('#theme-select');
const storedTheme = localStorage.getItem('ab620-theme') || 'auto';
function applyTheme(theme) { document.documentElement.dataset.theme = theme; themeSelect.value = theme; }
applyTheme(storedTheme);
themeSelect.addEventListener('change', (event) => { localStorage.setItem('ab620-theme', event.target.value); applyTheme(event.target.value); });
const list = $('#question-list'); const card = $('#question-card');
const topics = [...new Set(questions.map((item) => item.topic))];
topics.forEach((topic) => $('#topic-filter').insertAdjacentHTML('beforeend', `<option value="${topic}">${topic}</option>`));
function filtered() { return questions.filter((item) => (state.topic === 'all' || item.topic === state.topic) && (!state.query || `${item.question} ${item.explanation} ${item.topic}`.toLowerCase().includes(state.query.toLowerCase()))); }
function save() { localStorage.setItem('ab620-answers', JSON.stringify(state.answers)); }
function updateProgress() { const completed = Object.keys(state.answers).length; const percent = Math.round((completed / questions.length) * 100); $('#completed-count').textContent = completed; $('#total-count').textContent = questions.length; $('#question-total').textContent = questions.length; $('#progress-percent').textContent = `${percent}%`; }
function renderList(items) { list.innerHTML = items.map((item) => `<button class="list-item ${item.id === questions[state.index].id ? 'active' : ''} ${state.answers[item.id] !== undefined ? 'done' : ''}" data-id="${item.id}" type="button"><span>Q${String(item.id).padStart(2, '0')}</span><span>${item.topic.split(' ')[0]}</span></button>`).join(''); list.querySelectorAll('button').forEach((button) => button.addEventListener('click', () => { state.index = questions.findIndex((item) => item.id === Number(button.dataset.id)); render(); })); }
function renderCard() { const item = questions[state.index]; const answered = state.answers[item.id]; const optionMarkup = item.options.map((option, index) => { let cls = ''; if (answered !== undefined && index === item.answer) cls = 'correct'; if (answered === index && index !== item.answer) cls = 'wrong'; return `<button class="option ${cls}" data-option="${index}" type="button"><span>${String.fromCharCode(65 + index)}</span>${option}</button>`; }).join(''); card.innerHTML = `<div class="question-meta"><span>${item.topic}</span><span>${item.official ? 'Microsoft Learn aligned' : 'Unofficial practice'}</span></div><h3>${item.question}</h3><div class="options">${optionMarkup}</div>${answered !== undefined ? `<div class="explanation"><strong>${answered === item.answer ? 'Correct answer' : `Correct answer: ${String.fromCharCode(65 + item.answer)}`}</strong>${item.explanation}<br /><br /><a class="source-link" href="${item.source}" target="_blank" rel="noreferrer">Read the Microsoft Learn source ↗</a></div>` : ''}<div class="question-footer"><button class="small-button" id="previous" type="button">← Previous</button><button class="small-button next" id="next" type="button">${state.index === questions.length - 1 ? 'Finish' : 'Next question →'}</button></div>`; card.querySelectorAll('.option').forEach((button) => button.addEventListener('click', () => { state.answers[item.id] = Number(button.dataset.option); save(); render(); })); $('#previous').addEventListener('click', () => { state.index = Math.max(0, state.index - 1); render(); }); $('#next').addEventListener('click', () => { state.index = Math.min(questions.length - 1, state.index + 1); render(); }); $('#question-number').textContent = item.id; }
function render() { const items = filtered(); if (!items.length) { list.innerHTML = '<p class="empty-state">No questions match this search.</p>'; card.innerHTML = '<div class="explanation"><strong>Nothing found</strong>Try a different keyword or reset the topic filter.</div>'; updateProgress(); return; } if (!items.some((item) => item.id === questions[state.index].id)) state.index = questions.findIndex((item) => item.id === items[0].id); renderList(items); renderCard(); updateProgress(); }
document.querySelectorAll('[data-mode]').forEach((button) => button.addEventListener('click', () => { state.mode = button.dataset.mode; if (state.mode === 'review') { const unanswered = questions.find((item) => state.answers[item.id] === undefined); state.index = unanswered ? unanswered.id - 1 : 0; } if (state.mode === 'exam') { state.topic = 'all'; state.query = ''; $('#topic-filter').value = 'all'; $('#search').value = ''; } document.querySelector('#exam').scrollIntoView({ behavior: 'smooth' }); render(); }));
$('#search').addEventListener('input', (event) => { state.query = event.target.value; render(); }); $('#topic-filter').addEventListener('change', (event) => { state.topic = event.target.value; render(); }); $('#reset-progress').addEventListener('click', () => { if (confirm('Reset all local progress?')) { state.answers = {}; save(); render(); } });
render();
